"""Add eating_disorder_probability column to assessments

Revision ID: 308c98143bdc
Revises: 4f7ad7da0344
Create Date: 2024-10-24 16:22:12.802968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308c98143bdc'
down_revision = '4f7ad7da0344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eating_disorder_probability', sa.Float(), nullable=True))
        batch_op.alter_column('eating_disorder',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('eating_disorder',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('eating_disorder_probability')

    # ### end Alembic commands ###
