"""Add eating_disorder column to assessments

Revision ID: 4f7ad7da0344
Revises: ab72d69f5141
Create Date: 2024-10-24 13:23:17.354017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7ad7da0344'
down_revision = 'ab72d69f5141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eating_disorder', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('eating_disorder')

    # ### end Alembic commands ###
